[project]
name = "faasr-complete"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faasr-py",
    "httpx>=0.28.1",
    "jsonschema>=4.23.0",
    "pydantic>=2.11.7",
    "pytest>=7.4.0",
    "python-dotenv>=1.2.2",
    "requests>=2.32.3",
    "sqlite-vec>=0.1.7",
]

[tool.uv.sources]
faasr-py = { git = "https://github.com/FaaSr/FaaSr-Backend" }
